print ("Vamos a multiplicar 3 numeros")
n1 = int( input (" Ingrese el primer numero"))
n2 = int( input (" Ingrese el segundo numero"))
n3 = int( input (" Ingrese el tercer numero"))
print("La suma es" ,(n1*n2*n3))
