print ("Vamos a hallar el promedio de 5 numeros")
n1 = int( input (" Ingrese el primer numero: "))
n2 = int( input (" Ingrese el segundo numero: "))
n3 = int( input (" Ingrese el tercer numero: "))
n4 = int( input (" Ingrese el cuarto numero: "))
n5 = int( input (" Ingrese el quinto numero: "))
print("El promedio es: " ,(n1+n2+n3+n4+n5/5))
